stages:
- name: build
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: |-
        python --version
        pwd && ls
        python ./testPython2/testPython.py
        python ./testPython.py
timeout: 60
notification: {}
