stages:
- name: build
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: |-
        python -v
        pwd
        python -m ./testPython2/testPython.py
timeout: 60
notification: {}
